### ISSUE TITLE
[HELP] cmake error: can't find openssl

### ISSUE THREAD

**Issue by jaydamani** [minecraft-linux/mcpelauncher-updates#1]
I am trying to run 
`cmake -DCMAKE_TOOLCHAIN_FILE=/opt/android-ndk/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86_64 .`
and I get this error:
> CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR SSL Crypto)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindOpenSSL.cmake:574 (find_package_handle_standard_args)
  Webserver/CMakeLists.txt:6 (find_package)
  
any ideas on where openssl root folder could be?

**Comment by ChristopherHX** [comment]
The openssl root folder is the folder where you cloned and built the openssl repository.

You have to build openssl ( 3.x.x ) and Protobuf for android.

This repository has a [github action workflow](https://github.com/minecraft-linux/mcpelauncher-updates/blob/main/.github/workflows/cmake.yml) which successfully builds this mod incl. dependencies.

[This program might allow you to run the workflow locally](https://github.com/ChristopherHX/runner.server), however I never tried it myself.

_This repository wasn't meant to be public visible and isn't worked on anymore, parts might be later merged into libc-shim_

**Comment by jaydamani** [comment]
sorry for the late reply, I had exams irl. I downloaded the latest appimage and it works now, I think the issue might be from the package on AUR.
