### ISSUE TITLE
symbols on 1.18

### ISSUE THREAD

**Issue by Lamfi** [minecraft-linux/mcpelauncher-updates#2]
What about symbols on 1.18 version ,  , can we get dump of invisible symbols? for future mods

**Comment by ChristopherHX** [comment]
If you mean by invisible symbols, these mojang has removed / stripped from the game in 1.16.210 ( or in 1.13.0.9 ). Then I never was able to get them, however I heard using the ida decompiler it could be possible to find the address of the invisible symbol.

This mod has nothing to do with hidden / invisible symbols, it's purpose was checking the game license and if it passes patching undefined visible symbols of the game so the launcher can load the game without failing to resolve symbols.
